#!/usr/bin/env ruby

require 'gtk2'
require 'vte'
require 'trollop'

require_relative 'lib/options_parser'
require_relative 'lib/main_window'
require_relative 'lib/notebook'

module Gvte
  Gtk.init
  win = MainWindow.new(OptionsParser::parse_argv ARGV).set_default_size(400, 400).set_resizable(true).set_decorated(true).show_all
  Gtk.main
end

